### ISSUE TITLE
Nepero

### ISSUE THREAD

**Issue by LuigiVessella** [LuigiVessella/exp#2]
Prof mi servirebbe un aiutino perchè non riesco ad estrarre le cifre decimali con l'operatore %, lo devo convertire in un intero il numero?

**Comment by FabioZTessitore** [comment]
di che parli?

**Comment by LuigiVessella** [comment]
La versione normale è fatta, ora carico quella che approssima alla 3 cifra decimale?

**Comment by LuigiVessella** [comment]
Ho fatto anche la parte due ma non so se vada bene in quel modo

**Comment by FabioZTessitore** [comment]
aggiusta
